dist: xenial
language: python
python:
  - "3.6"
matrix:
  include:
    - python: 3.6
      env: KERAS="true"
    - python: 3.6
      env: KERAS="false"
    - python: 3.7
      env: KERAS="true"
    - python: 3.7
      env: KERAS="false"
install:
  - pip install --upgrade pip
  - pip install flake8
  - pip install -r requirements.txt
  - if [[ "$KERAS" == "true" ]]; then
      pip install keras;
      pip install tensorflow;
    fi
before_script:
  # stop the build if there are Python syntax errors or undefined names
  - flake8 . --count --select=E901,E999,F821,F822,F823 --ignore=E266 --show-source --statistics
  # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
  - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --ignore=E266 --statistics
script:
  - make test
after_success:
  - coverage combine --append
  - coveralls
  - codecov
